### 채널 수집 (youtubers.me로 기본)

In [1]:
# 기본 베이스 1000
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'https://us.youtubers.me/korea-republic-of/all/top-1000-youtube-channels-in-korea-republic-of'
page = requests.get(url)

soup = BeautifulSoup(page.content, 'lxml')

# 현재 페이지에서 table 태그 모두 선택하기
table1 = soup.select('table')

# 하나의 테이블 태그 선택하기
table = table1[0]

df_top1000 = pd.read_html(str(table))[0]

# 데이터프레임 선택하기
# table_df = table_df_list[0]
print(df_top1000)

     rank            Youtuber  subscribers  video views  video count  \
0       1           김프로KIMPRO   35500000.0  35520859913         2873
1       2   JYP Entertainment   28900000.0  22128318459         2047
2       3    MBCentertainment    9020000.0  17441904653       102823
3       4          Mnet K-POP   20900000.0  16024038220        36280
4       5                GH'S   19300000.0  14577720610          784
..    ...                 ...          ...          ...          ...
995   996               Vstar     400000.0    397750303         8281
996   997  삼성전자 Samsung Korea     712000.0    397690835          502
997   998              재훍 영상툰     781000.0    397669915          263
998   999                중앙일보     468000.0    396888804        14055
999  1000                진정부부     885000.0    396474767          375

             category  started
0      People & Blogs     2017
1               Music     2008
2       Entertainment     2009
3       Entertainment     2006
4              Gaming     2020
..                ...      ...
995     Entertainment     2015
996     Entertainment     2013
997  Film & Animation     2019
998   News & Politics     2014
999    People & Blogs     2013

[1000 rows x 7 columns]

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\564898138.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

In [2]:
def collect_youtuberme_url(category_url):
    page = requests.get(url)
    # Parse the HTML content
    soup = BeautifulSoup(page.content, "html.parser")

    # Find the table with class "top-charts"
    table = soup.find("table", class_="top-charts")

    # Find all <a> tags within the table
    href_list = []
    if table:
        for a_tag in table.find_all("a"):
            href_value = a_tag.get("href")
            if href_value.endswith("/youtuber-stats"):
                href_list.append("https://us.youtubers.me/" + href_value)

    # Print the list of href values
#     print(href_list)
    return href_list

In [3]:
# Test1
url = "https://us.youtubers.me/korea-republic-of/music/top-1000-music-youtube-channels-in-korea-republic-of"
url_list = collect_youtuberme_url(url)
print(len(url_list))

747

In [4]:
# Test2
page = requests.get(url)

soup = BeautifulSoup(page.content, 'lxml')

# 현재 페이지에서 table 태그 모두 선택하기
table1 = soup.select('table')

# 하나의 테이블 태그 선택하기
table = table1[0]

df_top1000 = pd.read_html(str(table))[0]
df_top1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\4072655203.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,JYP Entertainment,28900000.0,22128318459,2047,Music,2008
1,2,officialpsy,18600000.0,11087485826,131,Music,2010
2,3,Stone Music Entertainment,10800000.0,10053568888,11231,Music,2011
3,4,BIGBANG,15100000.0,8194740038,776,Music,2005
4,5,Jaeguchi,5240000.0,5678030197,1033,Music,2016
...,...,...,...,...,...,...,...
742,743,새파란귤,6440.0,0,0,Music,2017
743,744,EL,27600.0,0,0,Music,2016
744,745,Trainee A,1320000.0,0,0,Music,2021
745,746,데일리케이팝,63100.0,0,0,Music,2015
746,747,msgflav0r,1090.0,0,0,Music,2011

In [5]:
# 여러 카테고리 확인

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def crawl_table_urls_extracted(start_url, table_class='top-charts', depth=1):
    visited_urls = set()
    excluded_urls = []
    extracted_strings = {}

    def extract_string_between_substrings(url, start_substring, end_substring):
        start_index = url.find(start_substring)
        end_index = url.find(end_substring, start_index + len(start_substring))
        if start_index != -1 and end_index != -1:
            return url[start_index + len(start_substring):end_index]
        return None

    def recursive_crawl(url, current_depth):
        if current_depth > depth:
            return

        try:
            response = requests.get(url)
            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')

                # Find the table with the specified class
                table = soup.find('table', class_=table_class)

                if table:
                    # Extract href attributes from anchor tags within the table
                    for row in table.find_all('tr'):
                        columns = row.find_all('td')
                        for col_index, col in enumerate(columns):
                            # Exclude href attributes from the column with the name "category"
                            if col.get_text(strip=True).lower() == 'category':
                                continue

                            hrefs = [a.get('href') for a in col.find_all('a', href=True)]

                            # Process the hrefs
                            for href in hrefs:
                                absolute_url = urljoin(url, href)

                                # Save URLs without "korea-republic-of"
                                if 'korea-republic-of' not in absolute_url.lower():
                                    excluded_urls.append(absolute_url)
                                else:
                                    visited_urls.add(absolute_url)

                                    # Extract and save strings between specified substrings
                                    extracted_string = extract_string_between_substrings(
                                        absolute_url,
                                        'https://us.youtubers.me/korea-republic-of/',
                                        '/top-1000-'
                                    )
                                    if extracted_string:
                                        # Create a set for each visited URL to remove duplicates
                                        extracted_strings.setdefault(absolute_url, set()).add(extracted_string)

                                    # Avoid revisiting the same URL
                                    if absolute_url not in visited_urls:
                                        # Recursively crawl the next level
                                        recursive_crawl(absolute_url, current_depth + 1)

        except Exception as e:
            print(f"Error crawling {url}: {e}")

    recursive_crawl(start_url, 1)

    # Convert sets to lists
    excluded_urls = list(set(excluded_urls))
    visited_urls = list(set(visited_urls))

    # Convert sets to lists within the extracted_strings dictionary
    for url, strings_set in extracted_strings.items():
        extracted_strings[url] = list(strings_set)

    return extracted_strings

# Example usage
start_url = 'https://us.youtubers.me/korea-republic-of/all/top-1000-youtube-channels-in-korea-republic-of'
extracted_strings = crawl_table_urls_extracted(start_url, table_class='top-charts', depth=1)

# category 통일(union 편하게)
def category_preprocessing(df):
    df['category'] = df['category'].replace('nan', 'all')

    # Mapping of old categories to new categories
    category_mapping = {'Gaming': 'gaming',
                        'Movies': 'movies',
                        'Music': 'music',
                        'Comedy': 'comedy',
                        'People & Blogs': 'people-blogs',
                        'Pets & Animals': 'pets-animals',
                        'Autos & Vehicles': 'autos-vehicles',
                        'Entertainment': 'entertainment',
                        'News & Politics': 'news-politics',
                        'Film & Animation': 'film-animation',
                        'Sports': 'sports',
                        'Science & Technology': 'science-technology',
                        'Shows': 'shows',
                        'Education': 'education',
                        'Travel & Events': 'travel-events',
                        'Howto & Style': 'howto-style',
                        'Nonprofits & Activism': 'nonprofits-activism',
                        'all': 'all'}

    # Map the old categories to the new categories
    df['category'] = df['category'].map(category_mapping)
    return df

# category df
def create_dataframe(extracted_strings):
    data = {'url': [], 'category': []}
    for url, categories in extracted_strings.items():
        for category in categories:
            data['url'].append(url)
            data['category'].append(category)

    df = pd.DataFrame(data)
    return df

df_category = create_dataframe(extracted_strings)

# Display the DataFrame
print(df_category)

                                                  url             category
0   https://us.youtubers.me/korea-republic-of/peop...         people-blogs
1   https://us.youtubers.me/korea-republic-of/musi...                music
2   https://us.youtubers.me/korea-republic-of/ente...        entertainment
3   https://us.youtubers.me/korea-republic-of/gami...               gaming
4   https://us.youtubers.me/korea-republic-of/news...        news-politics
5   https://us.youtubers.me/korea-republic-of/spor...               sports
6   https://us.youtubers.me/korea-republic-of/all/...                  all
7   https://us.youtubers.me/korea-republic-of/film...       film-animation
8   https://us.youtubers.me/korea-republic-of/scie...   science-technology
9   https://us.youtubers.me/korea-republic-of/show...                shows
10  https://us.youtubers.me/korea-republic-of/trav...        travel-events
11  https://us.youtubers.me/korea-republic-of/come...               comedy
12  https://us.youtubers.me/korea-republic-of/pets...         pets-animals
13  https://us.youtubers.me/korea-republic-of/howt...          howto-style
14  https://us.youtubers.me/korea-republic-of/educ...            education
15  https://us.youtubers.me/korea-republic-of/auto...       autos-vehicles
16  https://us.youtubers.me/korea-republic-of/nonp...  nonprofits-activism

In [8]:
# url = 'https://us.youtubers.me/korea-republic-of/all/top-1000-youtube-channels-in-korea-republic-of'
url = "https://us.youtubers.me/korea-republic-of/music/top-1000-music-youtube-channels-in-korea-republic-of"
def collect_youtuberme_basic(url):
    page = requests.get(url)

    soup = BeautifulSoup(page.content, 'lxml')

    # 현재 페이지에서 table 태그 모두 선택하기
    table1 = soup.select('table')

    # 하나의 테이블 태그 선택하기
    table = table1[0]

    df_top1000 = pd.read_html(str(table))[0]
    print("df1000:", len(df_top1000))
    href_list = collect_youtuberme_url(url)
    df_top1000['url'] = href_list
    print("url_list: ", len(href_list))
    df_top1000 = category_preprocessing(df_top1000)
    return df_top1000
# collect_youtuberme_basic(url)
dfs = []
for url in df_category['url'].to_list():
#     print(collect_youtuberme_basic(url))
    df_new = collect_youtuberme_basic(url)
    dfs.append(df_new)
#         result_df = pd.concat([result_df, df_new], ignore_index=True)
result_df = pd.concat(dfs, axis=0, ignore_index=True)
result_df = result_df.drop_duplicates()
result_df = result_df.drop("rank", axis=1)
result_df

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 747
url_list:  747

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 573
url_list:  573

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 541
url_list:  541

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 707
url_list:  707

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 169
url_list:  169

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 6
url_list:  6

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 217
url_list:  217

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 395
url_list:  395

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 315
url_list:  315

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 540
url_list:  540

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 329
url_list:  329

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 272
url_list:  272

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 53
url_list:  53

,Youtuber,subscribers,video views,video count,category,started,url
0,김프로KIMPRO,35500000.0,35520859913,2873,people-blogs,2017,https://us.youtubers.me//kimpro/youtuber-stats
1,Byungari 병아리언니,8770000.0,7245254567,879,people-blogs,2020,https://us.youtubers.me//byungari/youtuber-stats
2,팀일루션 노성율 - TEAM1LLUSION,6620000.0,7236264357,871,people-blogs,2010,https://us.youtubers.me//team1llusion/youtuber...
3,TwinRoozi 쌍둥이 루지,10700000.0,6743867013,587,people-blogs,2018,https://us.youtubers.me//twinroozi/youtuber-stats
4,Hongyu ASMR 홍유,15700000.0,5571730035,738,people-blogs,2018,https://us.youtubers.me//hongyu-asmr/youtuber-...
...,...,...,...,...,...,...,...
8859,全能神教會粵語頻道,5860.0,41813,16,nonprofits-activism,2016,https://us.youtubers.me//9d7ee9a1-548c-46b0-b7...
8860,Anonymous Messengers,491.0,2528,6,nonprofits-activism,2016,https://us.youtubers.me//anonymous-e144fd85-35...
8861,네더고래의 대.단.한 채널.,5950.0,563,1,nonprofits-activism,2012,https://us.youtubers.me//9156ecfa-d5fc-4838-b6...
8862,오렌지LAB,8020.0,0,0,nonprofits-activism,2018,https://us.youtubers.me//lab-7938026b-07f6-4e1...
8863,Álan V,954.0,0,0,nonprofits-activism,2016,https://us.youtubers.me//koreia-clash/youtuber...

In [9]:
# category 통일(union 편하게)
def category_preprocessing(df):
    df['category'] = df['category'].replace('nan', 'all')

    # Mapping of old categories to new categories
    category_mapping = {'Gaming': 'gaming',
                        'Movies': 'movies',
                        'Music': 'music',
                        'Comedy': 'comedy',
                        'People & Blogs': 'people-blogs',
                        'Pets & Animals': 'pets-animals',
                        'Autos & Vehicles': 'autos-vehicles',
                        'Entertainment': 'entertainment',
                        'News & Politics': 'news-politics',
                        'Film & Animation': 'film-animation',
                        'Sports': 'sports',
                        'Science & Technology': 'science-technology',
                        'Shows': 'shows',
                        'Education': 'education',
                        'Travel & Events': 'travel-events',
                        'Howto & Style': 'howto-style',
                        'Nonprofits & Activism': 'nonprofits-activism',
                        'all': 'all'}

    # Map the old categories to the new categories
    df['category'] = df['category'].map(category_mapping)
    return df

# category df
def create_dataframe(extracted_strings):
    data = {'url': [], 'category': []}
    for url, categories in extracted_strings.items():
        for category in categories:
            data['url'].append(url)
            data['category'].append(category)

    df = pd.DataFrame(data)
    return df

df_category = create_dataframe(extracted_strings)

# Display the DataFrame
print(df_category)

                                                  url             category
0   https://us.youtubers.me/korea-republic-of/peop...         people-blogs
1   https://us.youtubers.me/korea-republic-of/musi...                music
2   https://us.youtubers.me/korea-republic-of/ente...        entertainment
3   https://us.youtubers.me/korea-republic-of/gami...               gaming
4   https://us.youtubers.me/korea-republic-of/news...        news-politics
5   https://us.youtubers.me/korea-republic-of/spor...               sports
6   https://us.youtubers.me/korea-republic-of/all/...                  all
7   https://us.youtubers.me/korea-republic-of/film...       film-animation
8   https://us.youtubers.me/korea-republic-of/scie...   science-technology
9   https://us.youtubers.me/korea-republic-of/show...                shows
10  https://us.youtubers.me/korea-republic-of/trav...        travel-events
11  https://us.youtubers.me/korea-republic-of/come...               comedy
12  https://us.youtubers.me/korea-republic-of/pets...         pets-animals
13  https://us.youtubers.me/korea-republic-of/howt...          howto-style
14  https://us.youtubers.me/korea-republic-of/educ...            education
15  https://us.youtubers.me/korea-republic-of/auto...       autos-vehicles
16  https://us.youtubers.me/korea-republic-of/nonp...  nonprofits-activism

### YouTuberme Dataframe 1차

In [10]:
dfs = []
for url in df_category['url'].to_list():
#     print(collect_youtuberme_basic(url))
    df_new = collect_youtuberme_basic(url)
    dfs.append(df_new)
#         result_df = pd.concat([result_df, df_new], ignore_index=True)
result_df = pd.concat(dfs, axis=0, ignore_index=True)
result_df = result_df.drop_duplicates()
result_df = result_df.drop("rank", axis=1)
result_df['youtube url'] = [url[:-7] for url in  result_df['url'].to_list()]
result_df

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 747
url_list:  747

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 573
url_list:  573

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 541
url_list:  541

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 1000
url_list:  1000

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 707
url_list:  707

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 169
url_list:  169

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 6
url_list:  6

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 217
url_list:  217

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 395
url_list:  395

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 315
url_list:  315

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 540
url_list:  540

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 329
url_list:  329

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 272
url_list:  272

C:\Users\HyunJunLee\AppData\Local\Temp\ipykernel_14056\3471236879.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_top1000 = pd.read_html(str(table))[0]

df1000: 53
url_list:  53

,Youtuber,subscribers,video views,video count,category,started,url,youtube url
0,김프로KIMPRO,35500000.0,35520859913,2873,people-blogs,2017,https://us.youtubers.me//kimpro/youtuber-stats,https://us.youtubers.me//kimpro/youtube
1,Byungari 병아리언니,8770000.0,7245254567,879,people-blogs,2020,https://us.youtubers.me//byungari/youtuber-stats,https://us.youtubers.me//byungari/youtube
2,팀일루션 노성율 - TEAM1LLUSION,6620000.0,7236264357,871,people-blogs,2010,https://us.youtubers.me//team1llusion/youtuber...,https://us.youtubers.me//team1llusion/youtube
3,TwinRoozi 쌍둥이 루지,10700000.0,6743867013,587,people-blogs,2018,https://us.youtubers.me//twinroozi/youtuber-stats,https://us.youtubers.me//twinroozi/youtube
4,Hongyu ASMR 홍유,15700000.0,5571730035,738,people-blogs,2018,https://us.youtubers.me//hongyu-asmr/youtuber-...,https://us.youtubers.me//hongyu-asmr/youtube
...,...,...,...,...,...,...,...,...
8859,全能神教會粵語頻道,5860.0,41813,16,nonprofits-activism,2016,https://us.youtubers.me//9d7ee9a1-548c-46b0-b7...,https://us.youtubers.me//9d7ee9a1-548c-46b0-b7...
8860,Anonymous Messengers,491.0,2528,6,nonprofits-activism,2016,https://us.youtubers.me//anonymous-e144fd85-35...,https://us.youtubers.me//anonymous-e144fd85-35...
8861,네더고래의 대.단.한 채널.,5950.0,563,1,nonprofits-activism,2012,https://us.youtubers.me//9156ecfa-d5fc-4838-b6...,https://us.youtubers.me//9156ecfa-d5fc-4838-b6...
8862,오렌지LAB,8020.0,0,0,nonprofits-activism,2018,https://us.youtubers.me//lab-7938026b-07f6-4e1...,https://us.youtubers.me//lab-7938026b-07f6-4e1...
8863,Álan V,954.0,0,0,nonprofits-activism,2016,https://us.youtubers.me//koreia-clash/youtuber...,https://us.youtubers.me//koreia-clash/youtube

In [18]:
import pandas as pd
from datetime import datetime
# Get today's date
today_date = datetime.today().strftime('%Y-%m-%d')

# File path with today's date appended
file_path = f"Youtube_Data_{today_date}.xlsx"

# Save the DataFrame to Excel with today's date in the filename
new_df = result_df.drop_duplicates(subset=['Youtuber'])
new_df.to_excel(file_path, index=False)

In [36]:
# Test
# URL of the webpage you want to scrape
url = result_df['url'][2]
print(url)
# Send a GET request to the webpage
response = requests.get(result_df['url'][2])

# Parse the HTML content
soup = BeautifulSoup(response.content, "html.parser")

# Find all anchor tags containing "youtube" at the end of the href attribute
youtube_links = []
for a_tag in soup.find_all("a", href=True):
    if a_tag["href"].endswith("youtube"):
        youtube_links.append(a_tag["href"])

# Print the collected YouTube links
for link in youtube_links:
    print(link)

https://us.youtubers.me//mbcentertainment/youtuber-stats
/mbcentertainment/youtube

### 수집 채널 URL 추가

In [33]:
df_category

                                                  url             category
0   https://us.youtubers.me/korea-republic-of/peop...         people-blogs
1   https://us.youtubers.me/korea-republic-of/musi...                music
2   https://us.youtubers.me/korea-republic-of/ente...        entertainment
3   https://us.youtubers.me/korea-republic-of/gami...               gaming
4   https://us.youtubers.me/korea-republic-of/news...        news-politics
5   https://us.youtubers.me/korea-republic-of/spor...               sports
6   https://us.youtubers.me/korea-republic-of/all/...                  all
7   https://us.youtubers.me/korea-republic-of/film...       film-animation
8   https://us.youtubers.me/korea-republic-of/scie...   science-technology
9   https://us.youtubers.me/korea-republic-of/show...                shows
10  https://us.youtubers.me/korea-republic-of/trav...        travel-events
11  https://us.youtubers.me/korea-republic-of/pets...         pets-animals
12  https://us.youtubers.me/korea-republic-of/come...               comedy
13  https://us.youtubers.me/korea-republic-of/howt...          howto-style
14  https://us.youtubers.me/korea-republic-of/educ...            education
15  https://us.youtubers.me/korea-republic-of/auto...       autos-vehicles
16  https://us.youtubers.me/korea-republic-of/nonp...  nonprofits-activism

In [60]:
# Update 시 기존에 있는거면 
import pandas as pd
from sqlalchemy import create_engine
# 유튜브 채널 들어가서 추가 데이터
df_channel_income = pd.DataFrame()
from bs4 import BeautifulSoup
import requests

# URL of the webpage you want to scrape
url = result_df['url'][0]
print(url)
# Send a GET request to the webpage
response = requests.get(result_df['url'][0])

# Parse the HTML content
soup = BeautifulSoup(response.content, "html.parser")

# Find all anchor tags containing "youtube" at the end of the href attribute
youtube_links = []
for a_tag in soup.find_all("a", href=True):
    if a_tag["href"].endswith("youtube"):
        youtube_links.append(a_tag["href"])

# Print the collected YouTube links
for link in youtube_links:
    print(link)

# for url, yt in zip(result_df['url'].to_list(), result_df['Youtuber'].to_list()):
#     print(yt, url)
#     page = requests.get(url)

#     soup = BeautifulSoup(page.content, 'lxml')
    
#     # 현재 페이지에서 table 태그 모두 선택하기
#     table1 = soup.select('table')

#     # 하나의 테이블 태그 선택하기
#     table = table1[0]
    
#     df_url = pd.read_html(str(table))[0]
#     df_url['Youtuber'] = [yt for x in range(len(df_url))]
#     df_channel_income = pd.concat([df_channel_income, df_url], ignore_index=True)
#     print(df_channel_income)

https://us.youtubers.me//kimpro/youtuber-stats
/kimpro/youtube

In [9]:
import schedule
import time
from sqlalchemy import create_engine

# 처음 DB에 추가할때
def append_channel(dataframe):
    engine = create_engine("mysql+pymysql://root:"+"2000"+"@127.0.0.1" + "/yt_db")
    conn = engine.connect()

    dataframe.to_sql(name='channel', con=engine, if_exists='append', index=False)
    conn.close()

In [11]:
# db 저장
append_channel(result_df)

In [19]:
result_df.dropna(subset=['url'], inplace=True)
result_df.to_excel("yotube_list.xlsx")

In [17]:
# weekly 업로드 진행
def update_channel(dataframe):
    engine = create_engine("mysql+pymysql://root:"+"2000"+"@127.0.0.1" + "/yt_db")
    conn = engine.connect()
    sql_query = 'SELECT * FROM channel'
    df = pd.read_sql(sql_query, engine)
    
    dataframe.to_sql(name='channel', con=engine, if_exists='update', index=False)
    conn.close()

In [13]:
import pandas as pd

refine_df = pd.read_excel("0326test.xlsx")

In [6]:
refine_df = refine_df.drop("Unnamed: 0", axis= 1)

In [16]:
refine_df = refine_df.drop_duplicates(subset=["Youtuber", "subscribers"], keep="first")

# Print the updated dataframe
refine_df.to_excel("0327test.xlsx", index=False)

### Shorts 수집

In [27]:
refine_df

NameError: name 'refine_df' is not defined

In [39]:
# 기존에 존재하다던 데이터 update 해서 다시 데이터 넣기
engine = create_engine("mysql+pymysql://root:"+"2000"+"@127.0.0.1" + "/yt_db")
existing_data = pd.read_sql('SELECT * FROM channel', engine)

# Check for duplicates based on the 'ID' column
duplicates = existing_data[existing_data['Youtuber'].isin(new_data['Youtuber'])]

# Update existing rows with new data
existing_data.update(new_data)

# Filter out rows that are duplicates
new_rows = new_data[~new_data['Youtuber'].isin(duplicates['Youtuber'])]

# Append new rows to the existing data
merged_data = pd.concat([existing_data, new_rows], ignore_index=True)

# Write the merged data back to the database
merged_data.to_sql('channel', engine, if_exists='replace', index=False)

,rank,Youtuber,subscribers,video views,video count,category,started,url,category_ranking
0,1,한국고전영화 Korean Classic Film,844000.0,338119500,370,Movies,2011,None,None
1,1,김프로KIMPRO,28400000.0,29282621107,2233,people-blogs,2017,https://us.youtubers.me/5f2ac6ed-7607-4084-8d9...,NAN
2,2,TwinRoozi 쌍둥이 루지,10600000.0,6676946688,553,people-blogs,2018,https://us.youtubers.me/skt-t1/youtuber-stats,NAN
3,3,Byungari 병아리언니,7540000.0,6372469710,772,people-blogs,2020,https://us.youtubers.me/805407e2-3ce6-4a72-a61...,NAN
4,4,팀일루션 노성율 - TEAM1LLUSION,5790000.0,6263576833,828,people-blogs,2010,https://us.youtubers.me/heykin-couple/youtuber...,NAN
...,...,...,...,...,...,...,...,...,...
7811,49,Anonymous Messengers,493.0,2525,6,nonprofits-activism,2016,https://us.youtubers.me/anonymous-e144fd85-358...,NAN
7812,50,네더고래의 대.단.한 채널.,5980.0,536,1,nonprofits-activism,2012,https://us.youtubers.me/wildbreeze/youtuber-stats,NAN
7813,51,오렌지LAB,8020.0,0,0,nonprofits-activism,2018,https://us.youtubers.me/650d2f3e-90b8-48ee-9ce...,NAN
7814,52,Álan V,959.0,0,0,nonprofits-activism,2016,https://us.youtubers.me/tv-825cb6e4-9590-4f10-...,NAN
7815,1,한국고전영화 Korean Classic Film,844000.0,338119500,370,movies,2011,https://us.youtubers.me/koreanfilm/youtuber-stats,NAN

In [ ]:
# selenium 부분

In [3]:
import pandas as pd
data = pd.read_excel("yt_data.xlsx")
youtuberme_df = pd.read_excel("youtuberme.xlsx")
duplicates = youtuberme_df.duplicated(subset=["Youtuber"])
youtuberme_df = youtuberme_df.drop_duplicates(subset=["Youtuber"])
youtube_url_df = pd.read_excel("youtube_url.xlsx")
duplicates = youtube_url_df.duplicated(subset=["Youtuber"])
youtube_url_df = youtube_url_df.drop_duplicates(subset=["Youtuber"])
print(youtuberme_df)
print(len(youtube_url_df))
merged_df = pd.merge(youtuberme_df, youtube_url_df, on="Youtuber", how="inner")
merged_df = merged_df.drop(columns = ["rank", "Unnamed: 0"])
merged_df

      rank                     Youtuber  subscribers  video views  \
0        1                    김프로KIMPRO   33700000.0  34004458275
1        2            JYP Entertainment   28800000.0  21920230400
2        3             MBCentertainment    9020000.0  17386975068
3        4                   Mnet K-POP   20800000.0  15904910448
4        5  Boram Tube Vlog [보람튜브 브이로그]   30500000.0  13724691597
...    ...                          ...          ...          ...
8672    48                    병원갈 땐, 굿닥        773.0        41741
8673    49         Anonymous Messengers        493.0         2526
8674    50              네더고래의 대.단.한 채널.       5960.0          558
8675    51                       Álan V        955.0            0
8676    52                       오렌지LAB       8020.0            0

      video count             category  started  \
0            2723         people-blogs     2017
1            2029                music     2008
2          102324        entertainment     2009
3           35764        entertainment     2006
4             229        entertainment     2012
...           ...                  ...      ...
8672           15  nonprofits-activism     2015
8673            6  nonprofits-activism     2016
8674            1  nonprofits-activism     2012
8675            0  nonprofits-activism     2016
8676            0  nonprofits-activism     2018

                                                    url
0         https://us.youtubers.me/junsst/youtuber-stats
1      https://us.youtubers.me/toctocsia/youtuber-stats
2     https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...
3     https://us.youtubers.me/yd-real-life/youtuber-...
4     https://us.youtubers.me/cbs-newsshow/youtuber-...
...                                                 ...
8672  https://us.youtubers.me/c511cada-17d1-4c93-b2e...
8673  https://us.youtubers.me/koreia-clash/youtuber-...
8674  https://us.youtubers.me/9156ecfa-d5fc-4838-b6d...
8675      https://us.youtubers.me/goodoc/youtuber-stats
8676  https://us.youtubers.me/arirang-radio/youtuber...

[7686 rows x 8 columns]
7160

,Youtuber,subscribers,video views,video count,category,started,url,youtube_url
0,김프로KIMPRO,33700000.0,34004458275,2723,people-blogs,2017,https://us.youtubers.me/junsst/youtuber-stats,https://us.youtubers.me/junsst/youtube
1,JYP Entertainment,28800000.0,21920230400,2029,music,2008,https://us.youtubers.me/toctocsia/youtuber-stats,https://us.youtubers.me/toctocsia/youtube
2,MBCentertainment,9020000.0,17386975068,102324,entertainment,2009,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...
3,Mnet K-POP,20800000.0,15904910448,35764,entertainment,2006,https://us.youtubers.me/yd-real-life/youtuber-...,https://us.youtubers.me/yd-real-life/youtube
4,Boram Tube Vlog [보람튜브 브이로그],30500000.0,13724691597,229,entertainment,2012,https://us.youtubers.me/cbs-newsshow/youtuber-...,https://us.youtubers.me/cbs-newsshow/youtube
...,...,...,...,...,...,...,...,...
7155,절대멘탈,56700.0,111560280,335,education,2022,https://us.youtubers.me/d7c6c182-cb02-4c19-a90...,https://us.youtubers.me/d7c6c182-cb02-4c19-a90...
7156,궁금TV무엇일까,262000.0,111363396,1451,education,2014,https://us.youtubers.me/northkorean-sunny/yout...,https://us.youtubers.me/northkorean-sunny/youtube
7157,Clay Zoo,220000.0,110007364,584,education,2016,https://us.youtubers.me/54b69d62-18f2-4899-a24...,https://us.youtubers.me/54b69d62-18f2-4899-a24...
7158,은근한 잡다한 지식,393000.0,109468908,600,education,2017,https://us.youtubers.me/082a0b82-0a9b-4e6d-98d...,https://us.youtubers.me/082a0b82-0a9b-4e6d-98d...
7159,행크TV,557000.0,108868078,814,education,2018,https://us.youtubers.me/da278d4d-50f8-4d7d-abf...,https://us.youtubers.me/da278d4d-50f8-4d7d-abf...

In [5]:
merged_df = merged_df.drop(columns = ["rank", "Unnamed: 0"])

KeyError: "['rank', 'Unnamed: 0'] not found in axis"

In [6]:
duplicates = youtuberme_df.duplicated(subset=["Youtuber"])
youtuberme_df = youtuberme_df.drop_duplicates(subset=["Youtuber"])
youtuberme_df
# Print the rows with duplicated values in the "Youtuber" column
# print(youtuberme_df[duplicates])

,rank,Youtuber,subscribers,video views,video count,category,started,url
0,1,김프로KIMPRO,33700000.0,34004458275,2723,people-blogs,2017,https://us.youtubers.me/junsst/youtuber-stats
1,2,JYP Entertainment,28800000.0,21920230400,2029,music,2008,https://us.youtubers.me/toctocsia/youtuber-stats
2,3,MBCentertainment,9020000.0,17386975068,102324,entertainment,2009,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...
3,4,Mnet K-POP,20800000.0,15904910448,35764,entertainment,2006,https://us.youtubers.me/yd-real-life/youtuber-...
4,5,Boram Tube Vlog [보람튜브 브이로그],30500000.0,13724691597,229,entertainment,2012,https://us.youtubers.me/cbs-newsshow/youtuber-...
...,...,...,...,...,...,...,...,...
8672,48,"병원갈 땐, 굿닥",773.0,41741,15,nonprofits-activism,2015,https://us.youtubers.me/c511cada-17d1-4c93-b2e...
8673,49,Anonymous Messengers,493.0,2526,6,nonprofits-activism,2016,https://us.youtubers.me/koreia-clash/youtuber-...
8674,50,네더고래의 대.단.한 채널.,5960.0,558,1,nonprofits-activism,2012,https://us.youtubers.me/9156ecfa-d5fc-4838-b6d...
8675,51,Álan V,955.0,0,0,nonprofits-activism,2016,https://us.youtubers.me/goodoc/youtuber-stats
8676,52,오렌지LAB,8020.0,0,0,nonprofits-activism,2018,https://us.youtubers.me/arirang-radio/youtuber...

In [7]:
merged_df.drop_duplicates('Youtuber')

,Youtuber,subscribers,video views,video count,category,started,url,youtube_url
0,김프로KIMPRO,33700000.0,34004458275,2723,people-blogs,2017,https://us.youtubers.me/junsst/youtuber-stats,https://us.youtubers.me/junsst/youtube
4,JYP Entertainment,28800000.0,21920230400,2029,music,2008,https://us.youtubers.me/toctocsia/youtuber-stats,https://us.youtubers.me/toctocsia/youtube
8,MBCentertainment,9020000.0,17386975068,102324,entertainment,2009,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...
12,Mnet K-POP,20800000.0,15904910448,35764,entertainment,2006,https://us.youtubers.me/yd-real-life/youtuber-...,https://us.youtubers.me/yd-real-life/youtube
16,Boram Tube Vlog [보람튜브 브이로그],30500000.0,13724691597,229,entertainment,2012,https://us.youtubers.me/cbs-newsshow/youtuber-...,https://us.youtubers.me/cbs-newsshow/youtube
...,...,...,...,...,...,...,...,...
10120,절대멘탈,56700.0,111560280,335,education,2022,https://us.youtubers.me/d7c6c182-cb02-4c19-a90...,https://us.youtubers.me/d7c6c182-cb02-4c19-a90...
10121,궁금TV무엇일까,262000.0,111363396,1451,education,2014,https://us.youtubers.me/northkorean-sunny/yout...,https://us.youtubers.me/northkorean-sunny/youtube
10122,Clay Zoo,220000.0,110007364,584,education,2016,https://us.youtubers.me/54b69d62-18f2-4899-a24...,https://us.youtubers.me/54b69d62-18f2-4899-a24...
10123,은근한 잡다한 지식,393000.0,109468908,600,education,2017,https://us.youtubers.me/082a0b82-0a9b-4e6d-98d...,https://us.youtubers.me/082a0b82-0a9b-4e6d-98d...
10124,행크TV,557000.0,108868078,814,education,2018,https://us.youtubers.me/da278d4d-50f8-4d7d-abf...,https://us.youtubers.me/da278d4d-50f8-4d7d-abf...

In [2]:
import pandas as pd
df = pd.read_excel("youtube_url.xlsx")
df

,Unnamed: 0,Youtuber,youtube_url
0,0,김프로KIMPRO,https://us.youtubers.me/junsst/youtube
1,1,JYP Entertainment,https://us.youtubers.me/toctocsia/youtube
2,2,MBCentertainment,https://us.youtubers.me/675dd8b0-7c15-4c3c-bf9...
3,3,Mnet K-POP,https://us.youtubers.me/yd-real-life/youtube
4,4,Boram Tube Vlog [보람튜브 브이로그],https://us.youtubers.me/cbs-newsshow/youtube
...,...,...,...
8142,8142,절대멘탈,https://us.youtubers.me/d7c6c182-cb02-4c19-a90...
8143,8143,궁금TV무엇일까,https://us.youtubers.me/northkorean-sunny/youtube
8144,8144,Clay Zoo,https://us.youtubers.me/54b69d62-18f2-4899-a24...
8145,8145,은근한 잡다한 지식,https://us.youtubers.me/082a0b82-0a9b-4e6d-98d...
8146,8146,행크TV,https://us.youtubers.me/da278d4d-50f8-4d7d-abf...